spring:
  profiles:
    active: dev

# 配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poetry?characterEncoding=UTF-8&useUnicode=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 1008
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true